#!/bin/bash
#
# battery-notify - Send alert message when battery is low
#
# Copyright (C) 2015, 2016 Gabriel Szasz <gabriel.szasz1@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#

battery_status="$(acpi -b | grep --color=never "Discharging")"

if [[ -n $battery_status ]]; then 
    battery="$(echo $battery_status | cut -d " " -f 2)"
    remaining_percentage=$(echo $battery_status | cut -d " " -f 4)
    remaining_time=$(echo $battery_status | cut -d " " -f 5)

    if [[ $remaining_time < 00:15:00 ]] ; then
        notify-send -u critical "BAT ${battery} LOW" "${remaining_percentage%,} ($remaining_time remaining)"
    fi
fi
