#!/bin/bash
#
# cconv - An ultimate currency convertor
#
# Copyright (C) 2015, 2016 Gabriel Szasz <gabriel.szasz1@gmail.com>
#
# Derived from the "Simple Bash Currency Converter" blog post published at
# "Productivity Sauce" blog by Dmitri Popov on Mar 14, 2013. See
# <http://www.linux-magazine.com/Online/Blogs/Productivity-Sauce>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [[ $# == 3 ]]; then
    wget -qO- "http://www.google.com/finance/converter?a=${1^^}&from=$2&to=${3^^}" |  sed '/res/!d;s/<[^>]*>//g';
else
    echo "USAGE: cconv <AMOUNT> <SRC_CURRENCY> <DEST_CURRENCY>"
fi
