#!/bin/bash
#
# docked-mode-toggle
#
# Switch i3 desktop between docked and undocked mode.
#
# Copyright (C) 2015, 2016 Gabriel Szasz <gabriel.szasz1@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Dock DisplayPort 1 (coupled with HDMI 1.4 output)
dock_dp1=$(xrandr -q | grep 'DP-1-1' | cut -d ' ' -f 2)
# Dock DisplayPort 2 (coupled with dual-link DVI output)
dock_dp2=$(xrandr -q | grep 'DP-1-2' | cut -d ' ' -f 2)
# Dock DisplayPort 3 (converted to analog VGA output)
dock_dp3=$(xrandr -q | grep 'DP-1-3' | cut -d ' ' -f 2)

# No docking station
if [[ $dock_dp1 == "disconnected" && $dock_dp2 == "disconnected" && $dock_dp3 == "disconnected" ]]; then
    xrandr --output DP-1-2 --off --output DP-1-1 --off --output DP-1-3 --off
    notify-send -u low "Docked Mode" "OFF"
# My docking station, two screens - first connected to DP-2 (DVI) and second to DP-1 (DisplayPort)
elif [[ $dock_dp1 == "connected" && $dock_dp2 == "connected" ]]; then
    xrandr --output DP-1-2 --right-of eDP-0 --auto --primary --output DP-1-1 --right-of DP-1-2 --auto
    i3-msg -q 'workspace1; move workspace to output eDP-0'
    i3-msg -q 'workspace2; move workspace to output DP-1-2'
    i3-msg -q 'workspace3; move workspace to output DP-1-1'
    notify-send -u low "Docked Mode" "ON"
# Guest docking staton, single screen connected to DP-1 (first DisplayPort or HDMI)
elif [[ $dock_dp1 == "connected" && $dock_dvi == "disconnected" && $dock_dp3 == "disconnected" ]]; then
    xrandr --output DP-1-1 --right-of eDP-0 --auto --primary
    i3-msg -q 'workspace1; move workspace to output eDP-0'
    i3-msg -q 'workspace2; move workspace to output DP-1-1'
    i3-msg -q 'workspace3; move workspace to output DP-1-1'
    notify-send -u low "Docked Mode" "ON"
# Guest docking staton, single screen connected to DP-2 (second DisplayPort or DVI)
elif [[ $dock_dp1 == "disconnected" && $dock_dp2 == "connected" && $dock_dp3 == "disconnected" ]]; then
    xrandr --output DP-1-2 --right-of eDP-0 --auto --primary
    i3-msg -q 'workspace1; move workspace to output eDP-0'
    i3-msg -q 'workspace2; move workspace to output DP-1-2'
    i3-msg -q 'workspace3; move workspace to output DP-1-2'
    notify-send -u low "Docked Mode" "ON"
# Guest docking staton, single screen connected to DP-3 (VGA)
elif [[ $dock_dp1 == "disconnected" && $dock_dp2 == "disconnected" && $dock_dp3 == "connected" ]]; then
    xrandr --output DP-1-3 --right-of eDP-0 --auto --primary
    i3-msg -q 'workspace1; move workspace to output eDP-0'
    i3-msg -q 'workspace2; move workspace to output DP-1-3'
    i3-msg -q 'workspace3; move workspace to output DP-1-3'
    notify-send -u low "Docked Mode" "ON"
fi
