#!/bin/bash
#
# presentation-mode - Switch i3 desktop to presentation mode
#
# Copyright (C) 2015, 2016 Gabriel Szasz <gabriel.szasz1@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#


if [ -n "$(xset -q | grep 'DPMS is Enabled')" ]; then
    xrandr --output DP-1 --auto
    xset s off -dpms
    xautolock -disable
    notify-send -u low "Presenatation Mode" "ON"
else
    xrandr --output DP-1 --off
    xset s on +dpms
    xautolock -enable
    notify-send -u low "Presenation Mode" "OFF"
fi
